-- Seed Data: Dishes (Sample - first 50 dishes)
-- Full data should be imported via CSV

INSERT INTO dishes (dish_id, name, category, is_quick, is_meal_prep, season, cuisine, notes) VALUES
  ('D001', 'Aachener Printen-Parfait', 'Dessert', FALSE, FALSE, NULL, NULL, NULL),
  ('D002', 'Aal Grün (Berliner Art)', 'Hauptgericht', FALSE, FALSE, NULL, NULL, NULL),
  ('D003', 'Aalrauch-Forellenaufstrich', 'Aufstrich', FALSE, FALSE, NULL, NULL, NULL),
  ('D004', 'Agnolotti mit Ricotta-Spinat', 'Hauptgericht', FALSE, FALSE, NULL, NULL, NULL),
  ('D005', 'Albondigas in Tomatensauce', 'Hauptgericht', FALSE, FALSE, NULL, NULL, NULL),
  ('D006', 'Apfelkompott', 'Süßspeise', FALSE, FALSE, NULL, NULL, NULL),
  ('D007', 'Apfelpfannkuchen', 'Süßspeise', FALSE, FALSE, NULL, NULL, NULL),
  ('D008', 'Apfelstrudel', 'Süßspeise', FALSE, FALSE, NULL, NULL, NULL),
  ('D009', 'Arancini (gefüllte Reisbällchen)', 'Snack', FALSE, FALSE, NULL, NULL, NULL),
  ('D010', 'Asia-Gemüsepfanne mit Tofu', 'Hauptgericht', FALSE, FALSE, NULL, NULL, NULL),
  ('D011', 'Aglio e Olio (Spaghetti)', 'Pasta', FALSE, FALSE, NULL, NULL, NULL),
  ('D012', 'Amatriciana (Pasta)', 'Pasta', FALSE, FALSE, NULL, NULL, NULL),
  ('D013', 'Arrabbiata (Pasta)', 'Pasta', FALSE, FALSE, NULL, NULL, NULL),
  ('D014', 'Artischockenrisotto', 'Hauptgericht', FALSE, FALSE, NULL, NULL, NULL),
  ('D015', 'Allgäuer Käsespätzle', 'Hauptgericht', FALSE, FALSE, NULL, NULL, NULL),
  ('D016', 'Antipasti-Gemüse aus dem Ofen', 'Beilage', FALSE, FALSE, NULL, NULL, NULL),
  ('D017', 'Apfelrotkohl (Beilage)', 'Beilage', FALSE, FALSE, NULL, NULL, NULL),
  ('D018', 'Ajo Blanco (Mandel-Knoblauchsuppe)', 'Suppe', FALSE, FALSE, NULL, NULL, NULL),
  ('D019', 'Ananas-Curry (Huhn)', 'Hauptgericht', FALSE, FALSE, NULL, NULL, NULL),
  ('D020', 'Ananas-Curry (Tofu)', 'Hauptgericht (vegetarisch)', FALSE, FALSE, NULL, NULL, NULL),
  ('D021', 'Austernpilz-Geschnetzeltes (vegan)', 'Hauptgericht (vegan)', FALSE, FALSE, NULL, NULL, NULL),
  ('D022', 'Ajvar-Hähnchenpfanne', 'Hauptgericht', FALSE, FALSE, NULL, NULL, NULL),
  ('D023', 'Arabische Linsensuppe', 'Suppe', FALSE, FALSE, NULL, NULL, NULL),
  ('D024', 'Ajiaco (Kartoffelsuppe)', 'Suppe', FALSE, FALSE, NULL, NULL, NULL),
  ('D025', 'Arme Ritter (klassisch)', 'Süßspeise', FALSE, FALSE, NULL, NULL, NULL),
  ('D026', 'Arme Ritter (pikant)', 'Snack', FALSE, FALSE, NULL, NULL, NULL),
  ('D027', 'Artischockensalat (mediterran)', 'Salat', FALSE, FALSE, NULL, NULL, NULL),
  ('D028', 'Auberginenröllchen (Ricottafüllung)', 'Vorspeise', FALSE, FALSE, NULL, NULL, NULL),
  ('D029', 'Auberginenröllchen (vegane Füllung)', 'Vorspeise', FALSE, FALSE, NULL, NULL, NULL),
  ('D030', 'Auberginen-Curry (indisch)', 'Hauptgericht', FALSE, FALSE, NULL, NULL, NULL),
  ('D031', 'Auberginen-Curry (mit Huhn)', 'Hauptgericht', FALSE, FALSE, NULL, NULL, NULL),
  ('D032', 'Austern (Gratin)', 'Vorspeise', FALSE, FALSE, NULL, NULL, NULL),
  ('D033', 'Avocado-Salat (frisch)', 'Salat', FALSE, FALSE, NULL, NULL, NULL),
  ('D034', 'Avocado-Suppe (kalt)', 'Suppe', FALSE, FALSE, NULL, NULL, NULL),
  ('D035', 'Avo-Toast (klassisch)', 'Snack', FALSE, FALSE, NULL, NULL, NULL),
  ('D036', 'Avo-Toast (mit Ei)', 'Snack', FALSE, FALSE, NULL, NULL, NULL),
  ('D037', 'Avo-Toast (vegan, Tomate)', 'Snack', FALSE, FALSE, NULL, NULL, NULL),
  ('D038', 'Ayran (Getränk)', 'Getränk', FALSE, FALSE, NULL, NULL, NULL),
  ('D039', 'Açaí-Bowl (klassisch)', 'Frühstück', FALSE, FALSE, NULL, NULL, NULL),
  ('D040', 'Açaí-Bowl (mit Erdnussbutter)', 'Frühstück', FALSE, FALSE, NULL, NULL, NULL),
  ('D041', 'Apfel-Crumble', 'Dessert', FALSE, FALSE, NULL, NULL, NULL),
  ('D042', 'Apfel-Birnen-Kompott', 'Dessert', FALSE, FALSE, NULL, NULL, NULL),
  ('D043', 'Aprikosenknödel (österreichisch)', 'Dessert', FALSE, FALSE, NULL, NULL, NULL),
  ('D044', 'Aligot (Kartoffel-Käse-Püree)', 'Beilage', FALSE, FALSE, NULL, NULL, NULL),
  ('D045', 'Anatolischer Bulgursalat (Kisir)', 'Salat', FALSE, FALSE, NULL, NULL, NULL),
  ('D046', 'Arroz con Pollo (Huhn)', 'Hauptgericht', FALSE, FALSE, NULL, NULL, NULL),
  ('D047', 'Apple Pie (klassisch)', 'Dessert', FALSE, FALSE, NULL, NULL, NULL),
  ('D048', 'Apfel-Sellerie-Salat (Waldorf-Art)', 'Salat', FALSE, FALSE, NULL, NULL, NULL),
  ('D049', 'Auberginen-Dip (Baba Ghanoush)', 'Vorspeise', FALSE, FALSE, NULL, NULL, NULL),
  ('D050', 'Ajvar-Pasta (vegetarisch)', 'Pasta', FALSE, FALSE, NULL, NULL, NULL),
  -- Quick meals
  ('D115', 'Chili con Carne', 'Hauptgericht', TRUE, TRUE, NULL, NULL, NULL),
  ('D116', 'Carbonara (klassisch)', 'Hauptgericht', TRUE, FALSE, NULL, NULL, NULL),
  ('D117', 'Currywurst mit Kartoffelecken', 'Hauptgericht', TRUE, FALSE, NULL, NULL, NULL),
  ('D118', 'Cevapcici mit Reis', 'Hauptgericht', TRUE, FALSE, NULL, NULL, NULL),
  ('D121', 'Curry-Geschnetzeltes mit Reis', 'Hauptgericht', TRUE, TRUE, NULL, NULL, NULL),
  ('D122', 'Caesar Salad (mit Hähnchen)', 'Hauptgericht', TRUE, FALSE, NULL, NULL, NULL),
  ('D123', 'Chili sin Carne', 'Hauptgericht', TRUE, TRUE, NULL, NULL, NULL),
  ('D124', 'Cremige Tomaten-Pasta', 'Hauptgericht', TRUE, TRUE, NULL, NULL, NULL),
  ('D125', 'Curry-Kartoffel-Pfanne', 'Hauptgericht', TRUE, TRUE, NULL, NULL, NULL),
  ('D126', 'Crêpes', 'Snack', TRUE, FALSE, NULL, NULL, NULL)
ON CONFLICT (dish_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  is_quick = EXCLUDED.is_quick,
  is_meal_prep = EXCLUDED.is_meal_prep;

